#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {        
        echo "starting databag"
        PATH=`cat /etc/databag/store_path.txt`
        mkdir -p "${PATH}/assets"
        cp -n /opt/databag/databag.db ${PATH}
        /usr/bin/databag 7000 ${PATH} > "${PATH}/service.log"
}                 
 
stop() {          
        echo "stopping databag"
        killall databag 
}
